project:
  type: website
  output-dir: _site
  resources:
    - assets/store/**
    - assets/merch/**

website:
  site-url: https://jamrbaserunningscience.netlify.app
  title: "Base Running Science™"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: articles.qmd
        text: Articles
      - href: notes.qmd
        text: Notes
      - href: merch.qmd
        text: Merch
      - href: contact.qmd
        text: Contact
      - href: quote.qmd
        text: Request a Quote
  page-footer:
    left:
      - text: "contact@jamrbaserunningscience.com"
        href: mailto:info@jamrbaserunningscience.com
    center:
      - icon: instagram
        href: https://instagram.com/baserunningscience/
      - icon: linkedin
        href: https://linkedin.com/in/jamr2021/

format:
  html:
    theme: flatly
    toc: false
    page-layout: full
    css: styles.css
